### ISSUE TITLE
Ошибка при создании суперпользователя PostgreSQL

### ISSUE THREAD

**Issue by Hazzari** [MoreliaTalk/morelia_server#62]
При использовании базы данных Postgres, выполняя команды:

python manage.py --table create ->>> Таблица создается успешно

python manage.py --table superuser ->>> Выходит ошибка:

**sqlobject.dberrors.DuplicateEntryError: UNIQUE constraint failed: user.uuid**

**Comment by stepanskryabin** [comment]
> python manage.py --table create ->>> Таблица создается успешно

у меня уже на этом шаге выходит ошибка. @Hazzari распиши подробнее версии постгрес и какую ветку morelia_server используешь?

**Comment by stepanskryabin** [comment]
ну и запусти подключение к постгрес в дебаг-режиме, вывод здесь размести.

**Comment by Hazzari** [comment]
> > python manage.py --table create ->>> Таблица создается успешно
> 
> у меня уже на этом шаге выходит ошибка. @Hazzari распиши подробнее версии постгрес, какой драйвер и какую ветку morelia_server используешь?


После фиксов ошибка стала вылезать раньше, на команде:
python manage.py --table create


Лог трейсбэка python:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 50, in <module>
    main()
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "manage.py", line 29, in main
    class_.createTable(ifNotExists=True)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/main.py", line 1504, in createTable
    constraints = conn.createTable(cls)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 536, in createTable
    self.query(createSql)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 435, in query
    return self._runWithConnection(self._query, s)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 431, in _query
    self._executeRetry(conn, c, s)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/postgres/pgconnection.py", line 257, in _executeRetry
    raise dberrors.ProgrammingError(msg)
sqlobject.dberrors.ProgrammingError: syntax error at or near "user"
LINE 1: CREATE TABLE **user** (
```

Лог базы данных:
```
database    |
database    | PostgreSQL Database directory appears to contain a database; Skipping initialization
database    |
database    | 2020-10-16 06:50:26.028 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
database    | 2020-10-16 06:50:26.029 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database    | 2020-10-16 06:50:26.029 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database    | 2020-10-16 06:50:26.033 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database    | 2020-10-16 06:50:26.067 UTC [27] LOG:  database system was shut down at 2020-10-16 06:50:21 UTC
database    | 2020-10-16 06:50:26.088 UTC [1] LOG:  database system is ready to accept connections
database    | 2020-10-16 06:50:39.497 UTC [34] ERROR:  syntax error at or near "user" at character 84
database    | 2020-10-16 06:50:39.497 UTC [34] STATEMENT:  ALTER TABLE message ADD CONSTRAINT user_id_exists FOREIGN KEY (user_id) REFERENCES user (uuid)

```

**Comment by stepanskryabin** [comment]
Да, у меня такой же баг вылезает. Надо посмотреть ещё в MariaDB будет ли вылезать эта ошибка.
Я простопредполагаю, что виновато не совсем корректное создание связей между таблицами.
