### ISSUE TITLE
Ошибка отправки регистрации через консольный клиент

### ISSUE THREAD

**Issue by Hazzari** [MoreliaTalk/morelia_server#76]
Код самого простого клиента:

```
import websockets
import asyncio
import json

reg_mes = {"type": "register_user",
           "data": {"user_config": [{
               "password": "Qwerty12345",
               "login": "User3",
               "email": "User3@user.com",
               "username": "User3"
           }], "meta": None},
           "jsonapi": {
               "version": "1.0"
           }}


async def sender():
    async with websockets.connect('ws://127.0.0.1:8888/ws') as websocket:
        message = json.dumps(reg_mes)
        await websocket.send(message)
        a = await websocket.recv()
        print(a)


if __name__ == '__main__':
    asyncio.run(sender())

```

На сервере происходит ошибка:

```
TRACE:    127.0.0.1:56814 - Connection made
TRACE:    127.0.0.1:56814 - ASGI [2] Started scope={'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'scheme': 'ws', 'server': ('127.0.0.1', 8888), 'client': ('127.0.0.1', 56814), 'root_path': '', 'path': '/ws', 'raw_path': '/ws', 'query_string': b'', 'headers': '<...>', 'subprotocols': []}
TRACE:    127.0.0.1:56814 - ASGI [2] Receive {'type': 'websocket.connect'}
TRACE:    127.0.0.1:56814 - ASGI [2] Send {'type': 'websocket.accept', 'subprotocol': None}
INFO:     ('127.0.0.1', 56814) - "WebSocket /ws" [accepted]
2020-10-19 01:07:40 | INFO     |          server           |     websocket_endpoint | line: 81 | Clients information: host: 127.0.0.1 port: 56814
2020-10-19 01:07:40 | DEBUG    |          server           |     websocket_endpoint | line: 84 | {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'scheme': 'ws', 'server': ('127.0.0.1', 8888), 'client': ('127.0.0.1', 56814), 'root_path': '', 'path': '/ws', 'raw_path': '/ws', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:8888'), (b'upgrade', b'websocket'), (b'connection', b'Upgrade'), (b'sec-websocket-key', b'Y1XHYSkDCmJbrEU+qgoxgg=='), (b'sec-websocket-version', b'13'), (b'sec-websocket-extensions', b'permessage-deflate; client_max_window_bits'), (b'user-agent', b'Python/3.8 websockets/8.1')], 'subprotocols': [], 'fastapi_astack': <contextlib.AsyncExitStack object at 0x7fea8f67bc10>, 'app': <fastapi.applications.FastAPI object at 0x7fea8f663280>, 'router': <fastapi.routing.APIRouter object at 0x7fea8f663550>, 'endpoint': <function websocket_endpoint at 0x7fea8f67e0d0>, 'path_params': {}}
TRACE:    127.0.0.1:56814 - ASGI [2] Receive {'type': 'websocket.receive', 'text': '<192 chars>'}
TRACE:    127.0.0.1:56814 - ASGI [2] Raised exception
2020-10-19 01:07:40 | DEBUG    |          server           |     websocket_endpoint | line: 88 | {'type': 'register_user', 'data': {'user_config': [{'password': 'Qwerty12345', 'login': 'User3', 'email': 'User3@user.com', 'username': 'User3'}], 'meta': None}, 'jsonapi': {'version': '1.0'}}
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 65, in __call__
    raise exc from None
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/fastapi/routing.py", line 228, in app
    await dependant.call(**values)
  File "./server.py", line 89, in websocket_endpoint
    client = controller.ProtocolMethods(data)
  File "./mod/controller.py", line 42, in __init__
    self._register_user()
  File "./mod/controller.py", line 167, in _register_user
    if self.__check_login(self.request.data.user[0].login):
TypeError: 'NoneType' object is not subscriptable
```

Не смог разобраться что не так с 167 строкой, 
но приходит в request  time=None flow=None message=None user=None meta=None
```
if self.__check_login(self.request.data.user[0].login):
```

**Comment by stepanskryabin** [comment]
```
reg_mes = {"type": "register_user",
           "data": {"user_config": [{
               "password": "Qwerty12345",
               "login": "User3",
               "email": "User3@user.com",
               "username": "User3"
           }], "meta": None},
           "jsonapi": {
               "version": "1.0"
           }}
```
user_config - нет такого ключа

**Comment by Hazzari** [comment]
> user_config - нет такого ключа

```
reg_mes = {"type": "register_user",
           "data": {"user": [{
               "password": "Qwerty12345",
               "login": "User3",
               "email": "User3@user.com",
               "username": "User3"
           }], "meta": None},
           "jsonapi": {
               "version": "1.0"
           }}


```


ошибка 

```
TRACE:    127.0.0.1:52196 - Connection made
TRACE:    127.0.0.1:52196 - ASGI [2] Started scope={'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'scheme': 'ws', 'server': ('127.0.0.1', 8888), 'client': ('127.0.0.1', 52196), 'root_path': '', 'path': '/ws', 'raw_path': '/ws', 'query_string': b'', 'headers': '<...>', 'subprotocols': []}
TRACE:    127.0.0.1:52196 - ASGI [2] Receive {'type': 'websocket.connect'}
TRACE:    127.0.0.1:52196 - ASGI [2] Send {'type': 'websocket.accept', 'subprotocol': None}
INFO:     ('127.0.0.1', 52196) - "WebSocket /ws" [accepted]
2020-10-19 11:17:01 | INFO     |          server           |     websocket_endpoint | line: 81 | Clients information: host: 127.0.0.1 port: 52196
2020-10-19 11:17:01 | DEBUG    |          server           |     websocket_endpoint | line: 84 | {'type': 'websocket', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'scheme': 'ws', 'server': ('127.0.0.1', 8888), 'client': ('127.0.0.1', 52196), 'root_path': '', 'path': '/ws', 'raw_path': '/ws', 'query_string': b'', 'headers': [(b'host', b'127.0.0.1:8888'), (b'upgrade', b'websocket'), (b'connection', b'Upgrade'), (b'sec-websocket-key', b'ZVH0Ta9285e0Fj03Wk6slw=='), (b'sec-websocket-version', b'13'), (b'sec-websocket-extensions', b'permessage-deflate; client_max_window_bits'), (b'user-agent', b'Python/3.8 websockets/8.1')], 'subprotocols': [], 'fastapi_astack': <contextlib.AsyncExitStack object at 0x7ff19756dc10>, 'app': <fastapi.applications.FastAPI object at 0x7ff197555280>, 'router': <fastapi.routing.APIRouter object at 0x7ff197555550>, 'endpoint': <function websocket_endpoint at 0x7ff1975700d0>, 'path_params': {}}
TRACE:    127.0.0.1:52196 - ASGI [2] Receive {'type': 'websocket.receive', 'text': '<185 chars>'}
2020-10-19 11:17:01 | DEBUG    |          server           |     websocket_endpoint | line: 88 | {'type': 'register_user', 'data': {'user': [{'password': 'Qwerty12345', 'login': 'User3', 'email': 'User3@user.com', 'username': 'User3'}], 'meta': None}, 'jsonapi': {'version': '1.0'}}
 1/Select  :  SELECT user_config.id, user_config.uuid, user_config.login, user_config.password, user_config.hash_password, user_config.username, user_config.is_bot, user_config.auth_id, user_config.email, user_config.avatar, user_config.bio, user_config.salt, user_config.key FROM user_config WHERE login = 'User3'
 1/QueryR  :  SELECT user_config.id, user_config.uuid, user_config.login, user_config.password, user_config.hash_password, user_config.username, user_config.is_bot, user_config.auth_id, user_config.email, user_config.avatar, user_config.bio, user_config.salt, user_config.key FROM user_config WHERE login = 'User3'
 1/COMMIT  :  auto
 1/QueryIns:  INSERT INTO user_config (uuid, login, password, hash_password, username, is_bot, auth_id, email, avatar, bio, salt, key) VALUES (399577801582, 'User3', 'Qwerty12345', 'e93650a50f7590f3362b83d76a803ec991b048a271ff2356c7d5406be1ac4f91', NULL, 'f', 'c4172e9c0db18a3e1fa86dfa586a6b38', NULL, NULL, NULL, 'X\201\310\271/\240n\360\323\320\254\247\341\020\2365'::bytea, '\225\374\200\021\251\215\311M\277\361\214:\370\210\305\326\341\022rz'::bytea) RETURNING id
 1/QueryR  :  INSERT INTO user_config (uuid, login, password, hash_password, username, is_bot, auth_id, email, avatar, bio, salt, key) VALUES (399577801582, 'User3', 'Qwerty12345', 'e93650a50f7590f3362b83d76a803ec991b048a271ff2356c7d5406be1ac4f91', NULL, 'f', 'c4172e9c0db18a3e1fa86dfa586a6b38', NULL, NULL, NULL, 'X\201\310\271/\240n\360\323\320\254\247\341\020\2365'::bytea, '\225\374\200\021\251\215\311M\277\361\214:\370\210\305\326\341\022rz'::bytea) RETURNING id
 1/COMMIT  :  auto
TRACE:    127.0.0.1:52196 - ASGI [2] Raised exception
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 154, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 65, in __call__
    raise exc from None
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 283, in handle
    await self.app(scope, receive, send)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/starlette/routing.py", line 57, in app
    await func(session)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/fastapi/routing.py", line 228, in app
    await dependant.call(**values)
  File "./server.py", line 89, in websocket_endpoint
    client = controller.ProtocolMethods(data)
  File "./mod/controller.py", line 42, in __init__
    self._register_user()
  File "./mod/controller.py", line 172, in _register_user
    models.UserConfig(uuid=gen_uuid,
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/main.py", line 1301, in __init__
    self._create(id, **kw)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/main.py", line 1352, in _create
    self._SO_finishCreate(id)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/main.py", line 1377, in _SO_finishCreate
    id = self._connection.queryInsertID(self,
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 492, in queryInsertID
    return self._runWithConnection(self._queryInsertID, soInstance, id,
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/postgres/pgconnection.py", line 295, in _queryInsertID
    self._executeRetry(conn, c, q)
  File "/Users/aleksan/.local/share/virtualenvs/morelia_server-IbBf8MB8/lib/python3.8/site-packages/sqlobject/postgres/pgconnection.py", line 259, in _executeRetry
    raise dberrors.DataError(ErrorMessage(e))
sqlobject.dberrors.DataError: integer out of range

```

**Comment by Hazzari** [comment]
Пересоздам
